language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
  matrix:
  - ROS_DISTRO=indigo USE_DEB=true ROS_PARALLEL_JOBS="-j8"
#  - ROS_DISTRO=indigo USE_DEB=false ROS_PARALLEL_JOBS="-j8" NOT_TEST_INSTALL="true"
script: source .travis/travis.sh
