language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
script: 
  - source .ci_config/travis.sh
  - source ./travis.sh
